name: pygtkwin environemnt
description: |
  Initializes pygtkwin environment
runs:
  using: composite
  steps:
    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - name: Set GTK_BUILD_NAME
      shell: bash
      run: echo 'GTK_BUILD_NAME=gtk${{ env.GTK_VERSION }}-${{ env.VCPKG_TRIPLET }}' >>$GITHUB_ENV

    - name: Set VCPKG_DIR
      shell: bash
      run: echo 'VCPKG_DIR=${{ github.workspace }}\vcpkg_installed\${{ env.VCPKG_TRIPLET }}' >>$GITHUB_ENV
